"""empty message

Revision ID: 27819c878d36
Revises: 9a9ab3e4a320
Create Date: 2022-03-22 16:03:15.048308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27819c878d36'
down_revision = '9a9ab3e4a320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'chief_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_user_chief_id', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_chief_id', 'user', ['chief_id'], unique=False)
    op.alter_column('user', 'chief_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
