"""empty message

Revision ID: 2aceeebda647
Revises: 4407ec7d5e5b
Create Date: 2022-03-22 08:26:47.626646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aceeebda647'
down_revision = '4407ec7d5e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_company_id_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_office_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'office', ['office_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.drop_constraint('vehicle_office_id_fkey', 'vehicle', type_='foreignkey')
    op.drop_constraint('vehicle_company_id_fkey', 'vehicle', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle', 'company', ['company_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'vehicle', 'office', ['office_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle', type_='foreignkey')
    op.drop_constraint(None, 'vehicle', type_='foreignkey')
    op.create_foreign_key('vehicle_company_id_fkey', 'vehicle', 'company', ['company_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('vehicle_office_id_fkey', 'vehicle', 'office', ['office_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_office_id_fkey', 'user', 'office', ['office_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('user_company_id_fkey', 'user', 'company', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
