"""empty message

Revision ID: 2c1d71449f70
Revises: a78a5ca5219b
Create Date: 2022-03-22 13:23:35.204059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1d71449f70'
down_revision = 'a78a5ca5219b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_chief_rel', 'office', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chief_rel', 'office', type_='foreignkey')
    # ### end Alembic commands ###
