"""empty message

Revision ID: 31cd49f6245f
Revises: 5b456829aa20
Create Date: 2022-03-22 12:52:26.917813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31cd49f6245f'
down_revision = '5b456829aa20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_chief_rel', 'user', 'user', ['chief_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chief_rel', 'user', type_='foreignkey')
    # ### end Alembic commands ###
