"""empty message

Revision ID: 41354e9e86b7
Revises: 6542f5b33842
Create Date: 2022-03-22 11:31:50.500252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41354e9e86b7'
down_revision = '6542f5b33842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_chief_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user', ['chief_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_chief_id_fkey', 'user', 'user', ['chief_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
