"""empty message

Revision ID: 4407ec7d5e5b
Revises: c08064af59f4
Create Date: 2022-03-21 20:36:37.124404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4407ec7d5e5b'
down_revision = 'c08064af59f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'company', 'user', ['owner_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'office', 'company', ['company_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'user', 'office', ['office_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'user', 'user', ['chief_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'vehicle', 'office', ['office_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'vehicle', 'company', ['company_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle', type_='foreignkey')
    op.drop_constraint(None, 'vehicle', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'office', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='foreignkey')
    # ### end Alembic commands ###
