"""empty message

Revision ID: 47261005620f
Revises: ccc294de7acb
Create Date: 2022-03-22 16:05:47.067667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47261005620f'
down_revision = 'ccc294de7acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_company_to_office_rel', 'company', type_='foreignkey')
    op.drop_constraint('fk_chief_rel', 'office', type_='foreignkey')
    op.drop_constraint('fk_company_rel', 'user', type_='foreignkey')
    op.drop_constraint('fk_office_rel', 'user', type_='foreignkey')
    op.drop_constraint('fk_chief_rel', 'user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_chief_rel', 'user', 'user', ['chief_id'], ['id'])
    op.create_foreign_key('fk_office_rel', 'user', 'office', ['office_id'], ['id'])
    op.create_foreign_key('fk_company_rel', 'user', 'company', ['company_id'], ['id'])
    op.create_foreign_key('fk_chief_rel', 'office', 'company', ['company_id'], ['id'])
    op.create_foreign_key('fk_company_to_office_rel', 'company', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
