"""empty message

Revision ID: 562adbb4f720
Revises: 31cd49f6245f
Create Date: 2022-03-22 12:54:13.795233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562adbb4f720'
down_revision = '31cd49f6245f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_company_rel', 'user', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_company_rel', 'user', type_='foreignkey')
    # ### end Alembic commands ###
