"""empty message

Revision ID: 5b456829aa20
Revises: c761892b73f1
Create Date: 2022-03-22 12:10:18.672464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b456829aa20'
down_revision = 'c761892b73f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_chief_id'), 'user', ['chief_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_chief_id'), table_name='user')
    # ### end Alembic commands ###
