"""empty message

Revision ID: 676f43192506
Revises: c7ed206fa53f
Create Date: 2022-03-23 16:22:31.443124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676f43192506'
down_revision = 'c7ed206fa53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_element_company_id', 'office', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_element_company_id', 'office', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###
