"""empty message

Revision ID: 78699db88305
Revises: e2732e56e807
Create Date: 2022-02-16 17:47:12.977916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78699db88305'
down_revision = 'e2732e56e807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_stafff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_stafff')
    # ### end Alembic commands ###
