"""empty message

Revision ID: 9a9ab3e4a320
Revises: 2c1d71449f70
Create Date: 2022-03-22 13:38:18.508473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9ab3e4a320'
down_revision = '2c1d71449f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_company_to_office_rel', 'company', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_company_to_office_rel', 'company', type_='foreignkey')
    # ### end Alembic commands ###
