"""empty message

Revision ID: c761892b73f1
Revises: 41354e9e86b7
Create Date: 2022-03-22 11:54:08.937896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c761892b73f1'
down_revision = '41354e9e86b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_chief_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user', ['chief_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_chief_id_fkey', 'user', 'user', ['chief_id'], ['id'])
    # ### end Alembic commands ###
