"""empty message

Revision ID: c7ed206fa53f
Revises: 47261005620f
Create Date: 2022-03-22 18:11:10.224649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ed206fa53f'
down_revision = '47261005620f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_element_company_id', 'office', 'company', ['company_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_element_company_id', 'office', type_='foreignkey')
    # ### end Alembic commands ###
