"""empty message

Revision ID: ccc294de7acb
Revises: 27819c878d36
Create Date: 2022-03-22 16:04:43.965462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc294de7acb'
down_revision = '27819c878d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_chief_id', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_chief_id', 'user', ['chief_id'], unique=False)
    # ### end Alembic commands ###
