"""empty message

Revision ID: dc28b76ecfe1
Revises: 1a60179af3c4
Create Date: 2022-02-16 18:35:34.488960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc28b76ecfe1'
down_revision = '1a60179af3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'owner_id')
    # ### end Alembic commands ###
