"""empty message

Revision ID: e7203f5cafac
Revises: 59c4799bdd53
Create Date: 2022-02-18 12:45:19.753337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7203f5cafac'
down_revision = '59c4799bdd53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chief_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_owner_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user', ['chief_id'], ['id'])
    op.drop_column('user', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_owner_id_fkey', 'user', 'user', ['owner_id'], ['id'])
    op.drop_column('user', 'chief_id')
    # ### end Alembic commands ###
